### PR TITLE
Jan 26th weekly

### PR DESCRIPTION
**Pull request by heather999**
@drphilmarshall  Now we're totally caught up - here is the Jan 26th weekly.  Viewable here:
https://heather999.github.io/Twinkles/weekly/

### CODE REVIEW

**Comment by heather999** [comment]
@drphilmarshall I'm going to update this PR with some additional weeklies.  I'll send another poke once we're ready to go.

**Comment by drphilmarshall** [comment]
Thanks, Heather!

**Comment by heather999** [comment]
@drphilmarshall Ok - all up to date now.  The link to the draft copy of the weeklies is here:
https://heather999.github.io/Twinkles/weekly/

**Comment by drphilmarshall** [comment]
Thanks Heather! Do you want to include today's weekly as well, while you're
at it?

**Comment by heather999** [comment]
Sure, I'll do that later today. I'll send a poke when it is ready.
Do we need to consider what becomes of the weeklies if this effort is brought under the umbrella of the full sims/dc1 group?

**Comment by drphilmarshall** [comment]
Maybe the DC2 project should produce weeklies? We have the technology now
:-)
We could offer it, at least.

**Comment by heather999** [comment]
Ok @drphilmarshall  - today's March 22nd weekly is all set too!

**Pull request merged**
