### PR TITLE
Update Matching Notebooks

### PR DESCRIPTION
**Pull request by jbkalmbach**
Update matching notebooks to use `gcr-catalogs`. Also make sure that they are doing what we want for DC2.

### CODE REVIEW

**Comment by jbkalmbach** [comment]
@drphilmarshall @jiwoncpark @dannygoldstein

This PR isn't quite ready but I just wanted it here for you all to follow along. 

These notebooks will have do 2 things as mentioned in #477

**Comment by jbkalmbach** [comment]
Ok, these are ready for comments.

Basically, `MatchingLensGalaxies.ipynb` and `MatchingLensGalaxies-SN.ipynb` run first and use an empirical fit between velocity dispersion and redshift to stellar mass in order to assign each lens galaxy in OM10/Danny's Lensed SNe catalog a stellar mass. It then matches this lens galaxy to a galaxy in the extragalactic catalog based upon this stellar mass and uses the radius, SED and SED normalization magnitude of this galaxy for input to PhoSim.

If @drphilmarshall and @jiwoncpark could look over `MatchingLensGalaxies.ipynb` and make sure everything looks good for strongly lensed AGN and @dannygoldstein could look over `MatchingLensGalaxies-SN.ipynb` to make sure everything looks good for the strongly lensed SNe that'd be great.

The other notebook `dc2_sprinkler_cache_production.ipynb` matches the lensed systems to the AGN that will be replaced by OM10 systems and the non-AGN galaxies that will be replaced by strongly lensed SNe systems in the uDDF field. This involves matching based upon redshift and magnitude for the AGN and only redshift for the SNe. If all of you could also take a look at this notebook and make sure that the bounds and matching criteria are reasonable that would be good.

I think the final thing I discussed with @jiwoncpark was making sure that the final matched AGN systems are good for analysis in DC2 and this will have to wait until we run all these notebooks with the final DC2 but I have included `data/cosmoDC2_v0.1_test_matched_AGN.fits` in order to provide an example of the catalog we will want to test.

**Comment by jbkalmbach** [comment]
Hi @drphilmarshall. I have updated the notebooks based upon your comments and used the cosmoDC2 v1.0 galaxies.

**Comment by drphilmarshall** [comment]
Great! Thanks Bryce.

**Pull request merged**
