### PR TITLE
changes to get travis-ci builds to succeed

### PR DESCRIPTION
**Pull request by jchiang87**
These changes include
* use sims 2.3.1 conda distribution
* add `from __future__ import absolute_import` and `print_function` to various files for python 3 compatibility
* add `future` and `scikit-learn` to conda installation
* install `OM10`

@danielsf There is one remaining python 3 compatibility change I didn't make, and it's [the last remaining failure](https://travis-ci.org/DarkEnergyScienceCollaboration/Twinkles/builds/173783739#L1211) for these builds: it's changing `unicode` to `str` [here](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/b0657f4de6fc3bb437b5406b11105a8e17701e24/python/desc/twinkles/twinklesDBConnections.py#L29).  Would this be ok to change?

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Hmm - looks like the PR travis test is failing, on the linter - but the push test passes! I am not sure what this means but I am inclined to merge this anyway. What do you think, @rbiswas4 @jchiang87 ?

**Comment by jchiang87** [comment]
Let me try to understand the difference between the pr and the push and try to fix the former if I can.  I'll post here with any news.

**Comment by jchiang87** [comment]
There were some commits in master that needed py3k fixes, so I merged master into this branch and fixed them (which we'd have to do eventually anyways).  So I'd say this is good to go.  @drphilmarshall

**Comment by rbiswas4** [comment]
This is great ... we will have a travis pass after a while!

**Comment by jchiang87** [comment]
Unless someone objects, I'll go ahead and merge this in the next couple of hours.

**Comment by rbiswas4** [comment]
Sure, but doesn't github block you unless you have a review (says merging is blocked) ...

**Comment by jchiang87** [comment]
Phil enabled admin privileges for me, but if you want to review this, then please go ahead...

**Comment by rbiswas4** [comment]
No, I was worried about the merge not being possible. I think it is good to merge anyway!

**Pull request merged**
